In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("C:/Users/Administrator/Downloads/sales_data.csv")
data

   OrderId     Product  Price
0        1      Laptop   5000
1        2       Phone  20000
2        3      Tablet  30000
3        4     Monitor  15000
4        5    Keyboard   2000
5        6       Mouse   1000
6        7     Printer  12000
7        8  Headphones   3000
8        9      Camera  25000
9       10     Speaker   4000

In [8]:
data=data.dropna()

In [9]:
data

   OrderId     Product  Price
0        1      Laptop   5000
1        2       Phone  20000
2        3      Tablet  30000
3        4     Monitor  15000
4        5    Keyboard   2000
5        6       Mouse   1000
6        7     Printer  12000
7        8  Headphones   3000
8        9      Camera  25000
9       10     Speaker   4000

In [11]:
data['price_with_tax']=data['Price']*1.18

In [12]:
data

   OrderId     Product  Price  price_with_tax
0        1      Laptop   5000          5900.0
1        2       Phone  20000         23600.0
2        3      Tablet  30000         35400.0
3        4     Monitor  15000         17700.0
4        5    Keyboard   2000          2360.0
5        6       Mouse   1000          1180.0
6        7     Printer  12000         14160.0
7        8  Headphones   3000          3540.0
8        9      Camera  25000         29500.0
9       10     Speaker   4000          4720.0

In [21]:
import sqlite3
connect3=sqlite3.connect("sales.db")
data.to_sql("sales_table",connect3,if_exists="replace",index=False)
print("data loaded success")
connect3.close()

data loaded success